[build-system]
requires = ["setuptools", "wheel", "requests", "grpcio-tools"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
